version: '3'

services:
  waf:
    build: waf
    depends_on:
      - jira
      - pull-crs
    networks:
      - jiranet
    ports:
      - "80:8001"
  pull-crs:
    build: cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jiranet
    # to troubleshoot: docker-compose exec pull-crs tail -F /pull-crs.log
  jira:
    depends_on:
      - postgresql
    image: blacklabelops/jira
    restart: always
    networks:
      - jiranet
    hostname: jira.aug.gr
    user: jira
    volumes:
      - /root/jira/volumes/jira/var/atlassian/jira:/var/atlassian/jira
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=CHANGEME'
      - 'SETENV_JVM_MINIMUM_MEMORY=384m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=1g'
      - 'JIRA_PROXY_NAME=jira.aug.gr'
      - 'JIRA_PROXY_PORT=80'
      - 'JIRA_PROXY_SCHEME=http'
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400

  postgresql:
    image: blacklabelops/postgres
    restart: always
    networks:
      - jiranet
    volumes:
      - /root/jira/volumes/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=CHANGEME'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge
